import Link from "next/link";
import { redirect } from "next/navigation";
import { canManageFinance } from "@/features/auth/permissions";
import { FinanceActions } from "@/features/finance/finance-actions";
import { InvoiceActions } from "@/features/finance/invoice-actions";
import { createSupabaseServerClient } from "@/lib/supabase/server";

type PageProps = { searchParams: Promise<{ notice?: string; error?: string }> };
const labels = { pending: "Pendente", paid: "Paga", overdue: "Vencida", cancelled: "Cancelada", reversed: "Estornada" } as const;
const tones = { pending: "maintenance", paid: "available", overdue: "inactive", cancelled: "inactive", reversed: "maintenance" } as const;
const money = (value: number) => value.toLocaleString("pt-BR", { style: "currency", currency: "BRL" });

export default async function FinancePage({ searchParams }: Readonly<PageProps>) {
  const [params, supabase] = await Promise.all([searchParams, createSupabaseServerClient()]); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect("/login");
  const { data: organizations } = await supabase.rpc("get_my_organizations"); const organization = organizations?.find((item) => item.status === "active"); if (!organization) redirect("/");
  const [{ data: invoices }, { data: tenants }, { data: contracts }] = await Promise.all([supabase.rpc("list_invoices", { target_organization_id: organization.id }), supabase.rpc("list_tenants", { target_organization_id: organization.id }), supabase.rpc("list_rental_contracts", { target_organization_id: organization.id })]);
  const records = invoices ?? []; const canManage = canManageFinance(organization.role); if (!canManage) redirect("/"); const open = records.filter((invoice) => invoice.status === "pending" || invoice.status === "overdue"); const receivable = open.reduce((sum, invoice) => sum + Number(invoice.amount_due) - Number(invoice.amount_paid), 0); const overdue = records.filter((invoice) => invoice.status === "overdue").reduce((sum, invoice) => sum + Number(invoice.amount_due) - Number(invoice.amount_paid), 0); const received = records.reduce((sum, invoice) => sum + Number(invoice.amount_paid), 0);
  return <><header className="admin-header"><div><p className="eyebrow">Gestão</p><h1>Financeiro — {organization.name}</h1></div><div className="topbar-actions">{canManage ? <FinanceActions contracts={contracts ?? []} invoices={records} organizationId={organization.id} tenants={tenants ?? []} /> : null}<Link className="button button--secondary" href="/">Voltar ao sistema</Link></div></header><section className="admin-content">{params.error ? <p className="form-message form-message--error">{params.error}</p> : null}{params.notice ? <p className="form-message form-message--notice">{params.notice}</p> : null}<section className="metrics finance-metrics"><article className="metric-card"><p>Contas a receber</p><strong>{money(receivable)}</strong><div>{open.length} fatura(s) em aberto</div></article><article className="metric-card"><p>Inadimplência</p><strong>{money(overdue)}</strong><div>{records.filter((invoice) => invoice.status === "overdue").length} fatura(s) vencida(s)</div></article><article className="metric-card"><p>Recebido</p><strong>{money(received)}</strong><div>Pagamentos registrados</div></article></section><article className="panel admin-panel"><header className="panel-header"><div><h2>Faturas e contas a receber</h2><p>Inclui histórico de contratos e locatários; ajustes e renegociações ficam registrados na fatura.</p></div></header>{records.length ? <div className="table-wrap"><table><thead><tr><th>Locatário</th><th>Vencimento</th><th>Composição</th><th>Valor</th><th>Pago</th><th>Saldo</th><th>Status</th>{canManage ? <th><span className="sr-only">Ações</span></th> : null}</tr></thead><tbody>{records.map((invoice) => { const additions = Number(invoice.additional_amount) + Number(invoice.fine_amount) + Number(invoice.interest_amount) + Number(invoice.extra_amount); const depositAndFees = Number(invoice.deposit_amount) + Number(invoice.fee_amount); return <tr key={invoice.id}><td><strong>{invoice.tenant_name}</strong><small className="table-subtitle">{invoice.contract_id ? "Vinculada a contrato" : "Cobrança avulsa"}</small></td><td>{new Date(`${invoice.due_on}T00:00:00`).toLocaleDateString("pt-BR")}</td><td><small>Base {money(Number(invoice.subtotal))}<br />Descontos {money(Number(invoice.discount_amount))}<br />Acréscimos {money(additions)}{depositAndFees !== 0 ? <><br />Caução e taxas {money(depositAndFees)}</> : null}</small></td><td>{money(Number(invoice.amount_due))}</td><td>{money(Number(invoice.amount_paid))}</td><td>{money(Number(invoice.amount_due) - Number(invoice.amount_paid))}</td><td><span className={`vehicle-status vehicle-status--${tones[invoice.status]}`}>{labels[invoice.status]}</span></td>{canManage ? <td><InvoiceActions invoice={invoice} organizationId={organization.id} /></td> : null}</tr>; })}</tbody></table></div> : <p className="empty-state">Nenhuma fatura registrada. Gere as cobranças recorrentes dos contratos ativos ou crie uma cobrança avulsa.</p>}</article></section></>;
}
