import Link from "next/link";
import { redirect } from "next/navigation";
import { canManageOperations } from "@/features/auth/permissions";
import { MaintenanceActions } from "@/features/fleet/maintenance-actions";
import { VehicleAssets } from "@/features/fleet/vehicle-assets";
import { formatPlate } from "@/features/fleet/vehicle-schema";
import { createSupabaseServerClient } from "@/lib/supabase/server";

type Props = { params: Promise<{ vehicleId: string }> };
const date = (value: string) => new Date(`${value}T00:00:00`).toLocaleDateString("pt-BR");

export default async function Page({ params }: Readonly<Props>) {
  const { vehicleId } = await params; const supabase = await createSupabaseServerClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect("/login");
  const { data: organizations } = await supabase.rpc("get_my_organizations"); const organization = organizations?.find((item) => item.status === "active"); if (!organization) redirect("/"); if (!canManageOperations(organization.role)) redirect("/frota");
  const [{ data: vehicles }, { data: odometer }, { data: maintenance }, { data: documents }, { data: accessories }] = await Promise.all([supabase.rpc("list_vehicles", { target_organization_id: organization.id }), supabase.rpc("list_vehicle_odometer_entries", { target_organization_id: organization.id, target_vehicle_id: vehicleId }), supabase.rpc("list_vehicle_maintenance", { target_organization_id: organization.id, target_vehicle_id: vehicleId }), supabase.rpc("list_vehicle_documents", { target_organization_id: organization.id, target_vehicle_id: vehicleId }), supabase.rpc("list_vehicle_accessories", { target_organization_id: organization.id, target_vehicle_id: vehicleId })]);
  const vehicle = vehicles?.find((item) => item.id === vehicleId); if (!vehicle) redirect("/frota");
  const canManage = canManageOperations(organization.role); const nowDate = new Date(); const today = nowDate.toISOString().slice(0, 10); const inThirtyDays = new Date(nowDate.getTime() + 30 * 86_400_000).toISOString().slice(0, 10);
  const alerts = [...(maintenance ?? []).filter((item) => item.status === "scheduled" && (item.scheduled_on <= today || (item.scheduled_odometer_km !== null && item.scheduled_odometer_km <= vehicle.odometer_km))).map((item) => `Manutenção pendente: ${item.title}`), ...(documents ?? []).filter((item) => item.expires_on !== null && item.expires_on <= inThirtyDays).map((item) => `Documento próximo do vencimento: ${item.name}`)];
  return <><header className="admin-header"><h1>{vehicle.brand} {vehicle.model} · {formatPlate(vehicle.plate)}</h1><Link className="button button--secondary" href="/frota">Voltar</Link></header><section className="admin-content">{alerts.length ? <article className="fleet-alerts" role="status"><strong>Atenção necessária</strong><ul>{alerts.map((alert) => <li key={alert}>{alert}</li>)}</ul></article> : null}<article className="panel admin-panel"><header className="panel-header"><h2>Histórico de quilometragem</h2></header>{odometer?.length ? <div className="table-wrap"><table><thead><tr><th>Data</th><th>Quilometragem</th><th>Observação</th></tr></thead><tbody>{odometer.map((item) => <tr key={item.id}><td>{date(item.recorded_on)}</td><td>{item.odometer_km.toLocaleString("pt-BR")} km</td><td>{item.note ?? "—"}</td></tr>)}</tbody></table></div> : <p className="empty-state">Nenhum registro de quilometragem.</p>}</article><article className="panel admin-panel"><header className="panel-header"><h2>Agenda e histórico de manutenção</h2></header>{maintenance?.length ? <div className="table-wrap"><table><thead><tr><th>Serviço</th><th>Tipo</th><th>Data</th><th>Status</th><th>Custo</th><th>Ação</th></tr></thead><tbody>{maintenance.map((item) => <tr key={item.id}><td>{item.title}</td><td>{item.type === "preventive" ? "Preventiva" : "Corretiva"}</td><td>{date(item.scheduled_on)}</td><td>{item.status}</td><td>{Number(item.cost).toLocaleString("pt-BR", { style: "currency", currency: "BRL" })}</td><td>{canManage && (item.status === "scheduled" || item.status === "in_progress") ? <MaintenanceActions maintenanceId={item.id} odometerKm={vehicle.odometer_km} organizationId={organization.id} /> : null}</td></tr>)}</tbody></table></div> : <p className="empty-state">Nenhuma manutenção agendada.</p>}</article><VehicleAssets accessories={accessories ?? []} canManage={canManage} documents={documents ?? []} organizationId={organization.id} vehicleId={vehicleId} /></section></>;
}
