"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { FormMessage } from "@/components/form-message";
import { Modal } from "@/components/modal";

type Document = { id: string; type: "crlv" | "insurance" | "inspection" | "other"; name: string; url: string; expires_on: string | null };
type Accessory = { id: string; name: string };
const documentTypes: Record<Document["type"], string> = { crlv: "CRLV", insurance: "Seguro", inspection: "Inspeção", other: "Outro" };

export function VehicleAssets({ organizationId, vehicleId, canManage, documents, accessories }: Readonly<{ organizationId: string; vehicleId: string; canManage: boolean; documents: Document[]; accessories: Accessory[] }>) {
  const router = useRouter(); const [kind, setKind] = useState<"document" | "accessory">("document"); const [open, setOpen] = useState(false); const [name, setName] = useState(""); const [url, setUrl] = useState(""); const [type, setType] = useState<Document["type"]>("crlv"); const [expiresOn, setExpiresOn] = useState(""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const save = async () => { setSaving(true); setError(""); const body = kind === "document" ? { kind, organizationId, name, type, url, expiresOn } : { organizationId, name }; const response = await fetch(`/api/vehicles/${vehicleId}/assets`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const data: { error?: string } = await response.json(); if (!response.ok) { setError(data.error ?? "Não foi possível salvar."); setSaving(false); return; } setOpen(false); setName(""); setUrl(""); setExpiresOn(""); setSaving(false); router.refresh(); };
  return <section className="vehicle-assets"><article className="panel admin-panel"><header className="panel-header"><div><h2>Documentos</h2><p>CRLV, seguro, inspeções e anexos.</p></div>{canManage ? <button className="button button--secondary" onClick={() => { setKind("document"); setOpen(true); }} type="button">Adicionar documento</button> : null}</header>{documents.length ? <div className="table-wrap"><table><thead><tr><th>Tipo</th><th>Documento</th><th>Validade</th></tr></thead><tbody>{documents.map((document) => <tr key={document.id}><td>{documentTypes[document.type]}</td><td><a className="table-action" href={document.url} rel="noreferrer" target="_blank">{document.name}</a></td><td>{document.expires_on ? new Date(`${document.expires_on}T00:00:00`).toLocaleDateString("pt-BR") : "—"}</td></tr>)}</tbody></table></div> : <p className="empty-state">Nenhum documento cadastrado.</p>}</article><article className="panel admin-panel"><header className="panel-header"><div><h2>Acessórios e opcionais</h2><p>Itens vinculados a este veículo.</p></div>{canManage ? <button className="button button--secondary" onClick={() => { setKind("accessory"); setOpen(true); }} type="button">Adicionar item</button> : null}</header>{accessories.length ? <ul className="asset-list">{accessories.map((accessory) => <li key={accessory.id}>{accessory.name}</li>)}</ul> : <p className="empty-state">Nenhum acessório ou opcional cadastrado.</p>}</article>{open ? <Modal onClose={() => setOpen(false)} title={kind === "document" ? "Adicionar documento" : "Adicionar acessório"}><FormMessage tone="error">{error}</FormMessage><div className="wizard-fields">{kind === "document" ? <><label>Tipo<select onChange={(event) => setType(event.target.value as Document["type"])} value={type}>{Object.entries(documentTypes).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>Nome<input maxLength={120} onChange={(event) => setName(event.target.value)} value={name} /></label><label>Link do arquivo<input onChange={(event) => setUrl(event.target.value)} placeholder="https://..." type="url" value={url} /></label><label>Validade (opcional)<input onChange={(event) => setExpiresOn(event.target.value)} type="date" value={expiresOn} /></label></> : <label>Nome do item<input maxLength={120} onChange={(event) => setName(event.target.value)} value={name} /></label>}<button className="button" disabled={saving} onClick={save} type="button">{saving ? "Salvando..." : "Salvar"}</button></div></Modal> : null}</section>;
}
