"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { FormMessage } from "@/components/form-message";
import { Modal } from "@/components/modal";
import { useToast } from "@/components/toast";
import { rentalContractSchema } from "@/features/contracts/contract-schema";
import { formatPlate } from "@/features/fleet/vehicle-schema";
import type { Tenant, Vehicle } from "@/lib/supabase/types";

type Props = { organizationId: string; tenants: Tenant[]; vehicles: Vehicle[] };
const frequencyLabels = { daily: "Diária", weekly: "Semanal", fortnightly: "Quinzenal", monthly: "Mensal", custom: "Personalizada" } as const;

export function ContractForm({ organizationId, tenants, vehicles }: Readonly<Props>) {
  const router = useRouter(); const { show } = useToast();
  const [open, setOpen] = useState(false); const [tenantId, setTenantId] = useState(""); const [vehicleId, setVehicleId] = useState(""); const [startsOn, setStartsOn] = useState(""); const [expectedReturnOn, setExpectedReturnOn] = useState(""); const [dailyRate, setDailyRate] = useState(""); const [depositAmount, setDepositAmount] = useState(""); const [billingFrequency, setBillingFrequency] = useState<keyof typeof frequencyLabels>("monthly"); const [billingTime, setBillingTime] = useState("09:00"); const [customInterval, setCustomInterval] = useState(""); const [customUnit, setCustomUnit] = useState<"day" | "week" | "month">("month"); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const close = () => { setOpen(false); setError(""); };
  const save = async () => { const parsed = rentalContractSchema.safeParse({ organizationId, tenantId, vehicleId, startsOn, expectedReturnOn, dailyRate, depositAmount: depositAmount || undefined, billingFrequency, billingTime, customInterval: billingFrequency === "custom" ? customInterval : undefined, customUnit: billingFrequency === "custom" ? customUnit : undefined }); if (!parsed.success) return setError(parsed.error.issues[0]?.message ?? "Revise os dados informados."); setSaving(true); setError(""); try { const response = await fetch("/api/contracts", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(parsed.data) }); const data: { error?: string } = await response.json(); if (!response.ok) throw new Error(data.error ?? "Não foi possível criar o contrato."); show("Contrato criado e veículo marcado como alugado."); router.push("/contratos"); router.refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Não foi possível criar o contrato."); setSaving(false); } };
  const activeTenants = tenants.filter((tenant) => tenant.status === "active"); const availableVehicles = vehicles.filter((vehicle) => vehicle.status === "available"); const selectedTenant = activeTenants.find((tenant) => tenant.id === tenantId);
  return <><button className="button" disabled={!activeTenants.length || !availableVehicles.length} onClick={() => setOpen(true)} type="button">Novo contrato</button>{open ? <Modal onClose={close} title="Novo contrato"><FormMessage tone="error">{error}</FormMessage><div className="wizard-fields"><label>Locatário<select onChange={(event) => setTenantId(event.target.value)} value={tenantId}><option value="">Selecione</option>{activeTenants.map((tenant) => <option key={tenant.id} value={tenant.id}>{tenant.full_name}{tenant.is_eligible ? "" : " (sem CNH válida)"}</option>)}</select>{selectedTenant && !selectedTenant.is_eligible ? <small className="field-hint">Este locatário não possui CNH válida cadastrada.</small> : null}</label><label>Veículo disponível<select onChange={(event) => setVehicleId(event.target.value)} value={vehicleId}><option value="">Selecione</option>{availableVehicles.map((vehicle) => <option key={vehicle.id} value={vehicle.id}>{vehicle.brand} {vehicle.model} · {formatPlate(vehicle.plate)}</option>)}</select></label><label>Início<input onChange={(event) => setStartsOn(event.target.value)} type="date" value={startsOn} /></label><label>Previsão de retorno<input min={startsOn || undefined} onChange={(event) => setExpectedReturnOn(event.target.value)} type="date" value={expectedReturnOn} /></label><label>Valor da diária (R$)<input inputMode="decimal" onChange={(event) => setDailyRate(event.target.value.replace(",", "."))} placeholder="0,00" value={dailyRate} /></label><label>Caução (opcional)<input inputMode="decimal" onChange={(event) => setDepositAmount(event.target.value.replace(",", "."))} placeholder="0,00" value={depositAmount} /></label><fieldset className="billing-fields"><legend>Recorrência de cobrança</legend><label>Frequência<select onChange={(event) => setBillingFrequency(event.target.value as keyof typeof frequencyLabels)} value={billingFrequency}>{Object.entries(frequencyLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>Horário da cobrança<input onChange={(event) => setBillingTime(event.target.value)} type="time" value={billingTime} /></label>{billingFrequency === "custom" ? <><label>Repetir a cada<input inputMode="numeric" min="1" onChange={(event) => setCustomInterval(event.target.value.replace(/\D/g, "").slice(0, 3))} value={customInterval} /></label><label>Unidade<select onChange={(event) => setCustomUnit(event.target.value as "day" | "week" | "month")} value={customUnit}><option value="day">dia(s)</option><option value="week">semana(s)</option><option value="month">mês(es)</option></select></label></> : null}</fieldset><button className="button" disabled={saving} onClick={save} type="button">{saving ? "Criando..." : "Criar contrato"}</button></div></Modal> : null}</>;
}
