import Link from "next/link";
import { redirect } from "next/navigation";
import { canManageFinance, canManageOperations } from "@/features/auth/permissions";
import { ContractForm } from "@/features/contracts/contract-form";
import { ContractActions } from "@/features/contracts/contract-actions";
import { formatPlate } from "@/features/fleet/vehicle-schema";
import { createSupabaseServerClient } from "@/lib/supabase/server";

type ContractsPageProps = { searchParams: Promise<{ error?: string; notice?: string }> };
const statusLabels: Record<"active" | "completed" | "cancelled", string> = { active: "Ativo", completed: "Concluído", cancelled: "Cancelado" };
const billingLabels: Record<"daily" | "weekly" | "fortnightly" | "monthly" | "custom", string> = { daily: "Diária", weekly: "Semanal", fortnightly: "Quinzenal", monthly: "Mensal", custom: "Personalizada" };
const billingLabel = (frequency: string | undefined) => billingLabels[frequency as keyof typeof billingLabels] ?? "Mensal";

export default async function ContractsPage({ searchParams }: Readonly<ContractsPageProps>) {
  const [params, supabase] = await Promise.all([searchParams, createSupabaseServerClient()]); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect("/login");
  const { data: organizations } = await supabase.rpc("get_my_organizations"); const organization = organizations?.find((item) => item.status === "active"); if (!organization) redirect("/");
  const [{ data: contracts }, { data: tenants }, { data: vehicles }] = await Promise.all([supabase.rpc("list_rental_contracts", { target_organization_id: organization.id }), supabase.rpc("list_tenants", { target_organization_id: organization.id }), supabase.rpc("list_vehicles", { target_organization_id: organization.id })]);
  const canManage = canManageOperations(organization.role); const canManageContractFinance = canManageFinance(organization.role);
  return <><header className="admin-header"><div><p className="eyebrow">Operação</p><h1>Contratos — {organization.name}</h1></div><div className="topbar-actions">{canManage ? <ContractForm organizationId={organization.id} tenants={tenants ?? []} vehicles={vehicles ?? []} /> : null}<Link className="button button--secondary" href="/">Voltar ao sistema</Link></div></header><section className="admin-content">{params.error ? <p className="form-message form-message--error" role="alert">{params.error}</p> : null}{params.notice ? <p className="form-message form-message--notice" role="status">{params.notice}</p> : null}<article className="panel admin-panel"><header className="panel-header"><div><h2>Locações</h2><p>{contracts?.length ?? 0} contrato(s) registrado(s).</p></div></header>{contracts?.length ? <div className="table-wrap"><table><thead><tr><th>Locatário</th><th>Veículo</th><th>Período</th><th>Diária</th><th>Cobrança</th><th>Status</th>{canManage ? <th><span className="sr-only">Ação</span></th> : null}</tr></thead><tbody>{contracts.map((contract) => { const frequency = contract.billing_frequency ?? "monthly"; const billingTime = contract.billing_time?.slice(0, 5) ?? "09:00"; return <tr key={contract.id}><td><strong>{contract.tenant_name}</strong></td><td>{contract.vehicle_brand} {contract.vehicle_model}<small className="table-subtitle">{formatPlate(contract.vehicle_plate)}</small></td><td>{new Date(`${contract.starts_on}T00:00:00`).toLocaleDateString("pt-BR")} — {new Date(`${contract.expected_return_on}T00:00:00`).toLocaleDateString("pt-BR")}</td><td>{Number(contract.daily_rate).toLocaleString("pt-BR", { style: "currency", currency: "BRL" })}</td><td>{billingLabel(frequency)} às {billingTime}{frequency === "custom" ? <small className="table-subtitle">A cada {contract.billing_custom_interval} {contract.billing_custom_unit === "day" ? "dia(s)" : contract.billing_custom_unit === "week" ? "semana(s)" : "mês(es)"}</small> : null}</td><td><span className={`vehicle-status vehicle-status--${contract.status === "active" ? "rented" : contract.status === "completed" ? "available" : "inactive"}`}>{statusLabels[contract.status]}</span></td>{canManage ? <td><ContractActions contract={{ ...contract, billing_frequency: frequency, billing_time: billingTime, billing_custom_interval: contract.billing_custom_interval ?? null, billing_custom_unit: contract.billing_custom_unit ?? null }} canManageFinance={canManageContractFinance} canManageOperations={canManage} organizationId={organization.id} /></td> : null}</tr>; })}</tbody></table></div> : <p className="empty-state">Nenhum contrato registrado. Cadastre um locatário e um veículo disponível para iniciar uma locação.</p>}</article></section></>;
}
