import { NextResponse } from "next/server";
import { invoiceAdjustmentSchema, invoiceFeeSchema, renegotiationSchema } from "@/features/finance/finance-schema";
import { recordAudit } from "@/lib/audit";
import { createSupabaseServerClient } from "@/lib/supabase/server";

type Context = { params: Promise<{ invoiceId: string }> };
export async function PATCH(request: Request, { params }: Context) {
  const payload: unknown = await request.json().catch(() => null); const { invoiceId } = await params; const action = typeof payload === "object" && payload !== null && "action" in payload ? payload.action : "adjust";
  const supabase = await createSupabaseServerClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) return NextResponse.json({ error: "Autenticação obrigatória." }, { status: 401 });
  if (action === "fee") { const parsed = invoiceFeeSchema.safeParse({ ...(typeof payload === "object" && payload !== null ? payload : {}), invoiceId }); if (!parsed.success) return NextResponse.json({ error: parsed.error.issues[0]?.message ?? "Dados inválidos." }, { status: 422 }); const { error } = await supabase.rpc("add_invoice_fee", { target_organization_id: parsed.data.organizationId, target_invoice_id: invoiceId, fee_description: parsed.data.description, fee_amount: parsed.data.amount }); if (error) return NextResponse.json({ error: "Não foi possível adicionar a taxa à fatura." }, { status: 409 }); await recordAudit(supabase, { organizationId: parsed.data.organizationId, action: "invoice.fee_added", entityType: "invoice", entityId: invoiceId, summary: `Taxa "${parsed.data.description}" de ${parsed.data.amount} adicionada`, metadata: { amount: parsed.data.amount } }); return NextResponse.json({ ok: true }); }
  if (action === "renegotiate") { const parsed = renegotiationSchema.safeParse({ ...(typeof payload === "object" && payload !== null ? payload : {}), invoiceId }); if (!parsed.success) return NextResponse.json({ error: parsed.error.issues[0]?.message ?? "Dados inválidos." }, { status: 422 }); const { error } = await supabase.rpc("renegotiate_invoice", { target_organization_id: parsed.data.organizationId, target_invoice_id: invoiceId, renegotiated_due_on: parsed.data.dueOn, renegotiated_amount: parsed.data.amount, renegotiation_description: parsed.data.description }); if (error) return NextResponse.json({ error: "Não foi possível renegociar a fatura. Confira o saldo e o status." }, { status: 409 }); await recordAudit(supabase, { organizationId: parsed.data.organizationId, action: "invoice.renegotiated", entityType: "invoice", entityId: invoiceId, summary: `Fatura renegociada para ${parsed.data.amount}`, metadata: { amount: parsed.data.amount, dueOn: parsed.data.dueOn } }); return NextResponse.json({ ok: true }); }
  const parsed = invoiceAdjustmentSchema.safeParse({ ...(typeof payload === "object" && payload !== null ? payload : {}), invoiceId }); if (!parsed.success) return NextResponse.json({ error: parsed.error.issues[0]?.message ?? "Dados inválidos." }, { status: 422 }); const { error } = await supabase.rpc("apply_invoice_adjustment", { target_organization_id: parsed.data.organizationId, target_invoice_id: invoiceId, adjustment_type: parsed.data.type, adjustment_amount: parsed.data.amount, adjustment_description: parsed.data.description });
  if (error) return NextResponse.json({ error: "Não foi possível atualizar a fatura. Confira o saldo e o status." }, { status: 409 });
  await recordAudit(supabase, { organizationId: parsed.data.organizationId, action: "invoice.adjusted", entityType: "invoice", entityId: invoiceId, summary: `Ajuste de ${parsed.data.type} (${parsed.data.amount})`, metadata: { type: parsed.data.type, amount: parsed.data.amount } });
  return NextResponse.json({ ok: true });
}
